
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khnvtxcnqozxluzzsemp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobnZ0eGNucW96eGx1enpzZW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTc4MTksImV4cCI6MjA2MDE3MzgxOX0.4AwPlBAI_Y4jdTOkoYQ7_E4kXspP4BG8ce13DFFn3W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use 'any' for now because the Database type doesn't include inventory_items yet
// This is a temporary workaround until we can regenerate the types
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
